# This source file is part of the Swift.org open source project
 #
 # Copyright (c) 2022 Apple Inc. and the Swift project authors
 # Licensed under Apache License v2.0 with Runtime Library Exception
 #
 # See https://swift.org/LICENSE.txt for license information
 # See https://swift.org/CONTRIBUTORS.txt for Swift project authors

 contact_links:
   - name: Discussion Forum
     url: https://forums.swift.org/tags/c/development/tooling/39/swift-syntax
     about: Ask and answer questions about SwiftSyntax
   - name: SwiftSyntax Documentation
     url: https://swiftpackageindex.com/swiftlang/swift-syntax/documentation/swiftsyntax
     about: Learn about how to use the SwiftSyntax in your projects
